// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtuSDNJsEnduZ53VvTSL31cL7Q5L6frAU',
    appId: '1:877617356828:web:e017b124a3bcd73c8effd9',
    messagingSenderId: '877617356828',
    projectId: 'efchat-50527',
    authDomain: 'efchat-50527.firebaseapp.com',
    storageBucket: 'efchat-50527.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7m-c5DJOk7gom0Lr65QXE4JNvOMVD704',
    appId: '1:877617356828:android:624be7a27e40f6cb8effd9',
    messagingSenderId: '877617356828',
    projectId: 'efchat-50527',
    storageBucket: 'efchat-50527.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc_3waZeXiXfWyMzJbN_Jk-w5SfiHIpjA',
    appId: '1:877617356828:ios:651226f8018f8b428effd9',
    messagingSenderId: '877617356828',
    projectId: 'efchat-50527',
    storageBucket: 'efchat-50527.appspot.com',
    iosBundleId: 'com.example.efrchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc_3waZeXiXfWyMzJbN_Jk-w5SfiHIpjA',
    appId: '1:877617356828:ios:e4a9bd980787633f8effd9',
    messagingSenderId: '877617356828',
    projectId: 'efchat-50527',
    storageBucket: 'efchat-50527.appspot.com',
    iosBundleId: 'com.example.efrchat.RunnerTests',
  );
}
